src/apps/quizzes/urls.py
from django.urls import path

from . import views

app_name = 'quizzes'

urlpatterns = [
  path('', views.IndexView.as_view(), name='index'),
  path('<slug:quiz_slug>/', views.QuizView.as_view(), name='quiz'),
  path('<slug:quiz_slug>/grade/', views.grade, name='grade'),
  path('<slug:quiz_slug>/submit/', views.submit, name='submit'),
]

src/django_quiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quizzes/', include('apps.quizzes.urls')),
]

src/quiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('apps.quizzes.urls')),
]

src/apps/quizzes/models.py
from django.db import models
from django.utils.text import slugify

class Quiz(models.Model):
  quiz_name = models.CharField(max_length=200)
  slug = models.SlugField(max_length=100, blank=True) #, unique=True) #add this once slugs have been created
  quiz_description = models.CharField(max_length=500,
                                      default="None")
  quiz_attempts = models.IntegerField(default=0)
  average_score = models.FloatField(default=0)
  active = models.BooleanField(default=False)

  class Meta:
    app_label = 'quizzes'

  def __str__(self) -> str:
    return self.quiz_name

  def save(self, *args, **kwargs):
    if not self.slug:
      self.slug = slugify(self.quiz_name)
    super().save(*args, **kwargs)


class Question(models.Model):
  quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
  question_text = models.CharField(max_length=200)
  question_completions = models.IntegerField(default=0)
  average_score = models.FloatField(default=0)

  class Meta:
    app_label = 'quizzes'

  def __str__(self) -> str:
    return self.question_text

class Choice(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  choice_text = models.CharField(max_length=200)
  selections = models.IntegerField(default=0)
  points = models.IntegerField(default=0)

  class Meta:
    app_label = 'quizzes'

  def __str__(self) -> str:
    return self.choice_text


class Rubric(models.Model):
  quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
  display_description = models.CharField(max_length=200)
  minimum_score = models.FloatField(default=0)
  tag = models.CharField(max_length=200, default="")
  count = models.IntegerField(default=0)

  class Meta:
    app_label = 'quizzes'

  def __str__(self) -> str:
    return f"{self.minimum_score} is required for {self.tag}"

src/apps/quizzes/forms.py
from django import forms

class QuizSubmissionForm(forms.Form):
  email = forms.EmailField(required=True)
  first_name = forms.CharField(required=True)
  last_name = forms.CharField(required=True)

src/apps/quizzes/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic

from .models import Quiz, Question, Choice, Rubric
from .forms import QuizSubmissionForm

from . import emails
class IndexView(generic.ListView):
  template_name = 'quizzes/index.html'
  context_object_name = 'quiz_list'

  def get_queryset(self):
    return Quiz.objects.filter(active=True)


class QuizView(generic.DetailView):
  model = Quiz
  template_name = 'quizzes/quiz.html'
  slug_field = 'slug'
  slug_url_kwarg = 'quiz_slug'


def grade(request, quiz_slug):
  # Grades the quiz, stores results in context, and redirects to the 
  # submission page.
  quiz = get_object_or_404(Quiz, slug=quiz_slug)
  form = QuizSubmissionForm(request.POST)
  context = {'quiz': quiz,
             'form': form}
  if request.method == 'POST':
    questions = quiz.question_set.all()
    score, unanswered = 0, 0
    for q in questions:
      try:
        pk = request.POST[f'question-{q.id}']
        selected_choice = q.choice_set.get(pk=pk)
        score += selected_choice.points
        selected_choice.selections += 1
        selected_choice.save()
        q.question_completions += 1
        q.average_score = q.average_score + (selected_choice.points - q.average_score) / q.question_completions
        q.save()
      except KeyError:
        unanswered += 1

    quiz.quiz_attempts += 1
    quiz.average_score = quiz.average_score + (score - quiz.average_score) / quiz.quiz_attempts
    quiz.save()

    rubric = _apply_rubric(quiz, score)
    context.update(rubric)
    context['score'] = score
    return render(request, 'quizzes/submit.html', context)

  return render(request, 'quizzes/quiz.html', context)


def submit(request, quiz_slug):
  context = {}
  if request.method == 'POST':
    quiz = get_object_or_404(Quiz, slug=quiz_slug)
    form = QuizSubmissionForm(request.POST)
    context['quiz'] = quiz
    if form.is_valid():
      emails.add_user_to_mailchimp(request.POST)
      emails.send_results_email(request.POST)
      return render(request, 'quizzes/success.html', context)

  context['form'] = QuizSubmissionForm(request.POST)
  return render(request, 'quizzes/submit.html', context)


def _apply_rubric(quiz, score):
  # Returns a dictionary of the rubric tag and description for the given
  # quiz and points.
  rubric = quiz.rubric_set.filter(quiz=quiz).order_by('-minimum_score')
  for r in rubric:
    if score >= r.minimum_score:
      r.count += 1
      r.save()
      return {'tag': r.tag,
              'display_description': r.display_description}
  # Return defaults
  return {'tag': quiz.quiz_name,
          'display_description': 'Thanks for taking the quiz!'}

src/apps/home/templates/home/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<html>
    <h1>
        Welcome to my quiz landing page!
    </h1>
    {% if quiz_list %}
    <ul>
        {% for quiz in quiz_list %}
        <li><a href="{% url 'home:quiz' quiz.id %}">{{ quiz.quiz_name }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
    <p>No quizzes are available. Check back soon!</p>
    {% endif %}
</html>
{% endblock %}

src/apps/home/templates/home/quiz_forms.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<html>
    <h1>
        {{ quiz.quiz_name }}
    </h1>
    {% for question in quiz.question_set.all %}
    <form action="{% url 'home:grade' quiz.id %}" method="post">
        {% csrf_token %}
        <ul>
            <fieldset>
                <legend><h2>
                    {{ question.question_text }}
                </h2></legend>
                {% for choice in question.choice_set.all %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label for="choice{{ forloop.counter }}">
                        {{ choice.choice_text }}
                    </label><br>
                    {% endfor %}
                    <br>
                    <input type="submit" value="Submit">
            </fieldset>
        </ul>
    </form>
    {% endfor %}

</html>
{% endblock %}

src/apps/home/templates/home/quiz_results.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>{{ quiz.quiz_name }}</h1>

<ul>
    <li>Total Points: {{ points }}</li>
    <li>Final Score: {{ score }}</li>
</ul>

<a href="{% url 'home:detail' question.id %}">Vote again?</a>


{% endblock %}

src/apps/quizzes/templates/quizzes/email.html
<html>
  <body>
    <p>Hello {{ first_name }} {{ last_name }}!
        Here are your quiz results!</p>
        <ul>
            <li>{{ display_description }}</li>
            <li>Final Score: {{ score }} points</li>
        </ul>
  </body>
</html>

src/apps/quizzes/templates/quizzes/index.html
<html>
    <h1>
        Welcome to my quiz landing page!
    </h1>
    {% if quiz_list %}
    <ul>
        {% for quiz in quiz_list %}
        <li>
            <a href="{% url 'quizzes:quiz' quiz.slug %}">{{ quiz.quiz_name }}</a>
            <p>{{ quiz.quiz_description }}</p>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
</html>

src/apps/quizzes/templates/quizzes/quiz.html
<html>
    <h1>
        {{ quiz.quiz_name }}
    </h1>
    <form action="{% url 'quizzes:grade' quiz.slug %}" method="POST">
        {% csrf_token %}
        {% for question in quiz.question_set.all %}
        <ul>
            <fieldset>
                <legend>{{ question.question_text }}</legend>
                {% for choice in question.choice_set.all %}
                <li>
                    <input type="radio" name="question-{{ question.id }}" id="id-{{ forloop.counter }}" value="{{ choice.id }}"/>
                    <label for="choice{{ forloop.counter}}">
                        {{ choice.choice_text }}
                    </label>
                    <br>
                </li>
                {% endfor %}
            </fieldset>
        </ul>
        {% endfor %}
        <input type="submit" value="Submit">
    </form>
</html>

src/apps/quizzes/templates/quizzes/submit.html
<html>
    <h1>
        Enter your email and have the results sent to you!
    </h1>
    <form action="{% url 'quizzes:submit' quiz.slug %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-action">
            <input type="hidden" name="score" value="{{ score }}">
            <input type="hidden" name="tag" value="{{ tag }}">
            <input type="hidden" name="display_description" value="{{ display_description }}">
            <button type="submit">Get my results!</button>
        </div>
    </form>
</html>

src/apps/quizzes/templates/quizzes/success.html
<html>
    <h1>
        Congrats! You just completed the {{ quiz.quiz_name }} quiz!
    </h1>
    <h2>
        Check your inbox for your results!
    </h2>
    <a href="{% url 'quizzes:quiz' quiz.slug %}">Try again if you think you can do better!</a>
</html>